permalink: /:categories/:title/
markdown: redcarpet
redcarpet:
  extensions:
      - no_intra_emphasis
      - tables
      - fenced_code_blocks
      - strikethrough
      - space_after_headers
      - highlight
      - quote
      - footnotes
      - hard_wrap
      - no_styles
